# Generated by Django 5.1.5 on 2025-02-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_personaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
