# Generated by Django 5.x on YYYY-MM-DD HH:MM
from django.db import migrations, models


def copy_personaldata_to_customuser(apps, schema_editor):
    # Get the historical models (safe for migrations)
    CustomUser = apps.get_model('authapp', 'CustomUser')
    PersonalData = apps.get_model('authapp', 'PersonalData')

    for pdata in PersonalData.objects.all():
        user_id = pdata.user_id
        try:
            user = CustomUser.objects.get(id=user_id)
            user.preferred_name = pdata.preferred_name
            user.b_day = pdata.b_day
            user.gender = pdata.gender
            user.save()
        except CustomUser.DoesNotExist:
            pass  # If somehow there's a PersonalData with no matching user, just skip


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_personaldata_gender'),  # or whatever your last migration is
    ]

    operations = [
        # 1. Add new fields to CustomUser
        migrations.AddField(
            model_name='customuser',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='b_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(blank=True, null=True,
                                      choices=[(1, 'Male'), (2, 'Female')]),
        ),

        # 2. Copy data from PersonalData into CustomUser
        migrations.RunPython(copy_personaldata_to_customuser, reverse_code=migrations.RunPython.noop),

        # 3. Delete the old PersonalData model
        migrations.DeleteModel(
            name='PersonalData',
        ),
    ]
