# Generated by Django 5.1.5 on 2025-02-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_personaldata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone", max_length=50),
        ),
    ]
