# Generated by Django 5.1.7 on 2025-04-03 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authapp', '0005_personaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken.'}, help_text='Required. 3-12 characters. Letters and digits only.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters and digits.', regex='^[A-Za-z0-9]+$'), django.core.validators.MinLengthValidator(3, 'Username must have at least 3 characters.'), django.core.validators.MaxLengthValidator(12, 'Username cannot exceed 12 characters.')], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='PersonalData',
        ),
    ]
