# Generated by Django 5.1.5 on 2025-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0006_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("was_success", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="SignupAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
