# Generated by Django 6.1.1 on 2026-09-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_loginattempt_signupattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
