# Generated by Django 6.1.1 on 2026-09-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_customuser_has_seen_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating_format',
            field=models.CharField(choices=[('numbers', 'Numbers'), ('words', 'Words')], default='numbers', max_length=8),
        ),
    ]
