"""
Django settings for ecosystem project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load DJANGO_SECRET_KEY (and any other local secrets) from a .env file next
# to manage.py, if present. Real deployments can still set the env var
# directly and skip the file.
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'testserver', '192.168.1.72', '.ngrok-free.app', '.ngrok.app']

# ngrok terminates HTTPS and forwards plain HTTP to us, and its free URLs
# change on every restart — trust any *.ngrok-free.app origin for CSRF so
# login/forms work over the tunnel without editing this file each time.
CSRF_TRUSTED_ORIGINS = ['https://*.ngrok-free.app', 'https://*.ngrok.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authapp',  # Login app
    'mainpage',  # Main page app
    'tracker',
    'landing',  # Public homepage
    # Mobile API (/api/v1/): DRF with JWT auth; the website keeps session auth
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'api',
]

LOGIN_URL = '/auth/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# WhiteNoise is useful for serving static files in production but it isn't
# required when running tests. Add it only if the package is installed.
try:
    import whitenoise  # noqa: F401
except ImportError:
    pass
else:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'ecosystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecosystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ecosystemdb',
        'USER': 'ecosystemuser',
        'PASSWORD': 'ecosystempass',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

AUTH_USER_MODEL = 'authapp.CustomUser'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Define static files URL and directories
STATIC_URL = '/static/'

# Directory where `collectstatic` will store all static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Include your app's static directory
STATICFILES_DIRS = [
    # NOTE: mainpage/ and authapp/ static dirs are already picked up by
    # Django's AppDirectoriesFinder (they're INSTALLED_APPS) - don't relist
    # them here, or collectstatic reports every one of their files as a
    # duplicate "found another file" conflict.
    os.path.join(BASE_DIR, 'project/cpp_server/static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# Mobile API (/api/v1/)
#
# Only the API's DRF views use these; the website's views keep Django's
# session authentication and CSRF. The iPhone app is a native client, not a
# browser origin, so no CORS headers are sent (django-cors-headers is not used).
# ---------------------------------------------------------------------------
from datetime import timedelta  # noqa: E402

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
    'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser'],
    'EXCEPTION_HANDLER': 'api.exceptions.handler',
    'DEFAULT_THROTTLE_RATES': {
        'auth': '20/min',        # login, signup, token refresh
        'sensitive': '10/min',   # export, clear logs, delete account
    },
    # Throttles key on the connecting address, not a client-supplied
    # X-Forwarded-For. Raise this if the API is ever put behind a proxy.
    'NUM_PROXIES': 0,
}

SIMPLE_JWT = {
    # Short-lived access tokens (kept in memory on the phone) and rotating
    # refresh tokens (kept in the iOS keychain). A used refresh token is
    # blacklisted as soon as it is exchanged.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_REFRESH_SERIALIZER': 'api.serializers.RefreshSerializer',
}
