# Generated by Django 5.1.5 on 2025-02-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField()),
                ('mood_rating', models.IntegerField(blank=True, null=True)),
                ('productivity_score', models.IntegerField(blank=True, null=True)),
                ('habits', models.TextField(blank=True, null=True)),
                ('hourly_activity', models.TextField(blank=True, null=True)),
                ('sleep_info', models.TextField(blank=True, null=True)),
                ('thoughts', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('user_id', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='HabitsLog',
        ),
        migrations.DeleteModel(
            name='HourlyActivity',
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
        migrations.DeleteModel(
            name='Productivity',
        ),
        migrations.DeleteModel(
            name='SleepLog',
        ),
        migrations.DeleteModel(
            name='Streak',
        ),
        migrations.DeleteModel(
            name='ThoughtsAndReflections',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
