# Generated by Django 5.1.5 on 2025-02-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_dailydata_delete_habitslog_delete_hourlyactivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='habits',
        ),
        migrations.RemoveField(
            model_name='dailydata',
            name='hourly_activity',
        ),
        migrations.RemoveField(
            model_name='dailydata',
            name='sleep_info',
        ),
        migrations.AddField(
            model_name='dailydata',
            name='goal_progress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='habits_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='hourly_activity_logging',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='sleep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='todo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
