# Generated by Django 5.1.5 on 2025-02-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_dailydata_habits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydata',
            old_name='goal_progress',
            new_name='self_reflection',
        ),
    ]

