# Generated by Django 5.1.5 on 2025-02-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_rename_goal_progress_dailydata_self_reflection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('streak_data', models.JSONField(default=dict)),
            ],
        ),
    ]
