# Generated by Django 5.1.5 on 2025-02-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('goal_text', models.TextField(blank=True)),
                ('habit_1', models.CharField(blank=True, max_length=100)),
                ('habit_2', models.CharField(blank=True, max_length=100)),
                ('habit_3', models.CharField(blank=True, max_length=100)),
                ('habit_4', models.CharField(blank=True, max_length=100)),
                ('habit_5', models.CharField(blank=True, max_length=100)),
                ('habit_6', models.CharField(blank=True, max_length=100)),
                ('habit_7', models.CharField(blank=True, max_length=100)),
                ('habit_8', models.CharField(blank=True, max_length=100)),
                ('habit_9', models.CharField(blank=True, max_length=100)),
                ('habit_10', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'unique_together': {('user_id', 'year', 'month')},
            },
        ),
    ]
