# Generated by Django 5.1.5 on 2025-03-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_remove_dailydata_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=50)),
            ],
        ),
    ]
