# Generated by Django 5.1.5 on 2025-04-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_activitymapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Streak',
        ),
        migrations.AddField(
            model_name='activitymapping',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitymapping',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activitymapping',
            unique_together={('user_id', 'name', 'year', 'month')},
        ),
    ]
