# Generated by Django 5.1.5 on 2025-04-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_monthlyactivitydiagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyactivitydiagram',
            name='image_path',
        ),
        migrations.AddField(
            model_name='monthlyactivitydiagram',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
