# Generated by Django 5.1.5 on 2025-04-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_remove_monthlyactivitydiagram_image_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyActivityDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('user_id', 'year')},
            },
        ),
    ]
